# Model arguments
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: open-r1/Mixture-of-Thoughts
dataset_config: code
dataset_test_split: test
eos_token: "<|endoftext|>"
dataset_prompt_column: messages
system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"

# GRPO trainer config
bf16: true
use_vllm: true
vllm_gpu_memory_utilization: 0.6
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-7B-MoT-GRPO
hub_strategy: every_save
learning_rate: 0
loss_type: dr_grpo
max_grad_norm: 0.2
beta: 0.0
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 5000
max_completion_length: 5000
max_length: 10000
pad_to_max_length: false
max_steps: -1
num_generations: 16
num_train_epochs: 1
output_dir: data/eval/Qwen2.5-7B-Instruct
overwrite_output_dir: false
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
push_to_hub: false
report_to:
- wandb
reward_funcs:
- code
- code_format
reward_weights:
- 1.0
- 0.1
code_provider: morph
save_strategy: "steps"
save_steps: 10
save_total_limit: 100
seed: 42
warmup_ratio: 0.1
do_eval: true
eval_strategy: "steps"
eval_steps: 10
eval_on_start: true
